
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://owlwhepibqcwdurmixjv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im93bHdoZXBpYnFjd2R1cm1peGp2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0OTQ3NzksImV4cCI6MjA1ODA3MDc3OX0.UkGi3hSQM197iUjP-1N1juBkYHvI9obHUg56vEt89rg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  }
});
